
import { Division, District, Upazila } from './types';

export const DIVISIONS: Division[] = [
  { id: 'dhaka', name: 'Dhaka' },
  { id: 'chattogram', name: 'Chattogram' },
  { id: 'rajshahi', name: 'Rajshahi' },
  { id: 'khulna', name: 'Khulna' },
  { id: 'barishal', name: 'Barishal' },
  { id: 'sylhet', name: 'Sylhet' },
  { id: 'rangpur', name: 'Rangpur' },
  { id: 'mymensingh', name: 'Mymensingh' },
];

export const DISTRICTS: District[] = [
  // Dhaka Division
  { id: 'dhaka-dist', divisionId: 'dhaka', name: 'Dhaka' },
  { id: 'gazipur', divisionId: 'dhaka', name: 'Gazipur' },
  { id: 'narayanganj', divisionId: 'dhaka', name: 'Narayanganj' },
  { id: 'tangail', divisionId: 'dhaka', name: 'Tangail' },
  { id: 'faridpur', divisionId: 'dhaka', name: 'Faridpur' },
  { id: 'manikganj', divisionId: 'dhaka', name: 'Manikganj' },
  { id: 'munshiganj', divisionId: 'dhaka', name: 'Munshiganj' },
  { id: 'narsingdi', divisionId: 'dhaka', name: 'Narsingdi' },
  { id: 'shariatpur', divisionId: 'dhaka', name: 'Shariatpur' },
  { id: 'madaripur', divisionId: 'dhaka', name: 'Madaripur' },
  { id: 'rajbari', divisionId: 'dhaka', name: 'Rajbari' },
  { id: 'gopalganj', divisionId: 'dhaka', name: 'Gopalganj' },
  { id: 'kishoreganj', divisionId: 'dhaka', name: 'Kishoreganj' },

  // Chattogram Division
  { id: 'chattogram-dist', divisionId: 'chattogram', name: 'Chattogram' },
  { id: 'coxsbazar', divisionId: 'chattogram', name: "Cox's Bazar" },
  { id: 'cumilla', divisionId: 'chattogram', name: 'Cumilla' },
  { id: 'feni', divisionId: 'chattogram', name: 'Feni' },
  { id: 'brahmanbaria', divisionId: 'chattogram', name: 'Brahmanbaria' },
  { id: 'chandpur', divisionId: 'chattogram', name: 'Chandpur' },
  { id: 'lakshmipur', divisionId: 'chattogram', name: 'Lakshmipur' },
  { id: 'noakhali', divisionId: 'chattogram', name: 'Noakhali' },
  { id: 'rangamati', divisionId: 'chattogram', name: 'Rangamati' },
  { id: 'khagrachhari', divisionId: 'chattogram', name: 'Khagrachhari' },
  { id: 'bandarban', divisionId: 'chattogram', name: 'Bandarban' },

  // Rajshahi Division
  { id: 'rajshahi-dist', divisionId: 'rajshahi', name: 'Rajshahi' },
  { id: 'bogura', divisionId: 'rajshahi', name: 'Bogura' },
  { id: 'pabna', divisionId: 'rajshahi', name: 'Pabna' },
  { id: 'sirajganj', divisionId: 'rajshahi', name: 'Sirajganj' },
  { id: 'naogaon', divisionId: 'rajshahi', name: 'Naogaon' },
  { id: 'natore', divisionId: 'rajshahi', name: 'Natore' },
  { id: 'joypurhat', divisionId: 'rajshahi', name: 'Joypurhat' },
  { id: 'chapainawabganj', divisionId: 'rajshahi', name: 'Chapainawabganj' },

  // Khulna Division
  { id: 'khulna-dist', divisionId: 'khulna', name: 'Khulna' },
  { id: 'jashore', divisionId: 'khulna', name: 'Jashore' },
  { id: 'satkhira', divisionId: 'khulna', name: 'Satkhira' },
  { id: 'bagerhat', divisionId: 'khulna', name: 'Bagerhat' },
  { id: 'chuadanga', divisionId: 'khulna', name: 'Chuadanga' },
  { id: 'jhenaidah', divisionId: 'khulna', name: 'Jhenaidah' },
  { id: 'kushtia', divisionId: 'khulna', name: 'Kushtia' },
  { id: 'magura', divisionId: 'khulna', name: 'Magura' },
  { id: 'meherpur', divisionId: 'khulna', name: 'Meherpur' },
  { id: 'narail', divisionId: 'khulna', name: 'Narail' },

  // Barishal Division
  { id: 'barishal-dist', divisionId: 'barishal', name: 'Barishal' },
  { id: 'bhola', divisionId: 'barishal', name: 'Bhola' },
  { id: 'jhalokati', divisionId: 'barishal', name: 'Jhalokati' },
  { id: 'patuakhali', divisionId: 'barishal', name: 'Patuakhali' },
  { id: 'pirojpur', divisionId: 'barishal', name: 'Pirojpur' },
  { id: 'barguna', divisionId: 'barishal', name: 'Barguna' },

  // Sylhet Division
  { id: 'sylhet-dist', divisionId: 'sylhet', name: 'Sylhet' },
  { id: 'moulvibazar', divisionId: 'sylhet', name: 'Moulvibazar' },
  { id: 'habiganj', divisionId: 'sylhet', name: 'Habiganj' },
  { id: 'sunamganj', divisionId: 'sylhet', name: 'Sunamganj' },

  // Rangpur Division
  { id: 'rangpur-dist', divisionId: 'rangpur', name: 'Rangpur' },
  { id: 'dinajpur', divisionId: 'rangpur', name: 'Dinajpur' },
  { id: 'kurigram', divisionId: 'rangpur', name: 'Kurigram' },
  { id: 'gaibandha', divisionId: 'rangpur', name: 'Gaibandha' },
  { id: 'nilphamari', divisionId: 'rangpur', name: 'Nilphamari' },
  { id: 'panchagarh', divisionId: 'rangpur', name: 'Panchagarh' },
  { id: 'thakurgaon', divisionId: 'rangpur', name: 'Thakurgaon' },
  { id: 'lalmonirhat', divisionId: 'rangpur', name: 'Lalmonirhat' },

  // Mymensingh Division
  { id: 'mymensingh-dist', divisionId: 'mymensingh', name: 'Mymensingh' },
  { id: 'jamalpur', divisionId: 'mymensingh', name: 'Jamalpur' },
  { id: 'netrokona', divisionId: 'mymensingh', name: 'Netrokona' },
  { id: 'sherpur', divisionId: 'mymensingh', name: 'Sherpur' },
];

export const UPAZILAS: Upazila[] = [
  // --- DHAKA DIVISION ---
  // Dhaka District
  { id: 'mirpur', districtId: 'dhaka-dist', name: 'Mirpur' },
  { id: 'dhanmondi', districtId: 'dhaka-dist', name: 'Dhanmondi' },
  { id: 'uttara', districtId: 'dhaka-dist', name: 'Uttara' },
  { id: 'gulshan', districtId: 'dhaka-dist', name: 'Gulshan' },
  { id: 'banani', districtId: 'dhaka-dist', name: 'Banani' },
  { id: 'mohammadpur', districtId: 'dhaka-dist', name: 'Mohammadpur' },
  { id: 'motijheel', districtId: 'dhaka-dist', name: 'Motijheel' },
  { id: 'new-market', districtId: 'dhaka-dist', name: 'New Market' },
  { id: 'shahbagh', districtId: 'dhaka-dist', name: 'Shahbagh' },
  { id: 'tejgaon', districtId: 'dhaka-dist', name: 'Tejgaon' },
  { id: 'khilgaon', districtId: 'dhaka-dist', name: 'Khilgaon' },
  { id: 'basundhara', districtId: 'dhaka-dist', name: 'Basundhara' },
  { id: 'badda', districtId: 'dhaka-dist', name: 'Badda' },
  { id: 'rampura', districtId: 'dhaka-dist', name: 'Rampura' },
  { id: 'farmgate', districtId: 'dhaka-dist', name: 'Farmgate' },
  { id: 'savar', districtId: 'dhaka-dist', name: 'Savar' },
  { id: 'keraniganj', districtId: 'dhaka-dist', name: 'Keraniganj' },
  { id: 'dhamrai', districtId: 'dhaka-dist', name: 'Dhamrai' },
  { id: 'dohar', districtId: 'dhaka-dist', name: 'Dohar' },
  { id: 'nawabganj', districtId: 'dhaka-dist', name: 'Nawabganj' },
  // Gazipur
  { id: 'gz-sadar', districtId: 'gazipur', name: 'Gazipur Sadar' },
  { id: 'kaliakair', districtId: 'gazipur', name: 'Kaliakair' },
  { id: 'kapasia', districtId: 'gazipur', name: 'Kapasia' },
  { id: 'sreepur', districtId: 'gazipur', name: 'Sreepur' },
  { id: 'kaliganj-gz', districtId: 'gazipur', name: 'Kaliganj' },
  // Narayanganj
  { id: 'ng-sadar', districtId: 'narayanganj', name: 'Narayanganj Sadar' },
  { id: 'rupganj', districtId: 'narayanganj', name: 'Rupganj' },
  { id: 'sonargaon', districtId: 'narayanganj', name: 'Sonargaon' },
  { id: 'araihazar', districtId: 'narayanganj', name: 'Araihazar' },
  { id: 'bandar', districtId: 'narayanganj', name: 'Bandar' },
  // Tangail
  { id: 'tg-sadar', districtId: 'tangail', name: 'Tangail Sadar' },
  { id: 'mirzapur', districtId: 'tangail', name: 'Mirzapur' },
  { id: 'kalihati', districtId: 'tangail', name: 'Kalihati' },
  { id: 'sakhipur', districtId: 'tangail', name: 'Sakhipur' },
  { id: 'basail', districtId: 'tangail', name: 'Basail' },
  { id: 'madhupur', districtId: 'tangail', name: 'Madhupur' },
  { id: 'ghatail', districtId: 'tangail', name: 'Ghatail' },
  { id: 'nagarpur', districtId: 'tangail', name: 'Nagarpur' },
  { id: 'delduar', districtId: 'tangail', name: 'Delduar' },
  { id: 'bhuapur', districtId: 'tangail', name: 'Bhuapur' },
  { id: 'gopalpur', districtId: 'tangail', name: 'Gopalpur' },
  { id: 'dhanbari', districtId: 'tangail', name: 'Dhanbari' },
  // Manikganj
  { id: 'mk-sadar', districtId: 'manikganj', name: 'Manikganj Sadar' },
  { id: 'singair', districtId: 'manikganj', name: 'Singair' },
  { id: 'shibalaya', districtId: 'manikganj', name: 'Shibalaya' },
  { id: 'saturia', districtId: 'manikganj', name: 'Saturia' },
  { id: 'harirampur', districtId: 'manikganj', name: 'Harirampur' },
  { id: 'ghior', districtId: 'manikganj', name: 'Ghior' },
  { id: 'daulatpur-mk', districtId: 'manikganj', name: 'Daulatpur' },
  // Munshiganj
  { id: 'ms-sadar', districtId: 'munshiganj', name: 'Munshiganj Sadar' },
  { id: 'srinagar', districtId: 'munshiganj', name: 'Srinagar' },
  { id: 'louhajang', districtId: 'munshiganj', name: 'Louhajang' },
  { id: 'tongibari', districtId: 'munshiganj', name: 'Tongibari' },
  { id: 'sirajdikhan', districtId: 'munshiganj', name: 'Sirajdikhan' },
  { id: 'gazaria', districtId: 'munshiganj', name: 'Gazaria' },
  // Narsingdi
  { id: 'ns-sadar', districtId: 'narsingdi', name: 'Narsingdi Sadar' },
  { id: 'raipura', districtId: 'narsingdi', name: 'Raipura' },
  { id: 'belabo', districtId: 'narsingdi', name: 'Belabo' },
  { id: 'monohardi', districtId: 'narsingdi', name: 'Monohardi' },
  { id: 'shibpur', districtId: 'narsingdi', name: 'Shibpur' },
  { id: 'palash', districtId: 'narsingdi', name: 'Palash' },
  // Kishoreganj
  { id: 'ks-sadar', districtId: 'kishoreganj', name: 'Kishoreganj Sadar' },
  { id: 'bhairab', districtId: 'kishoreganj', name: 'Bhairab' },
  { id: 'karimganj', districtId: 'kishoreganj', name: 'Karimganj' },
  { id: 'bajitpur', districtId: 'kishoreganj', name: 'Bajitpur' },
  { id: 'kuliarchar', districtId: 'kishoreganj', name: 'Kuliarchar' },
  { id: 'pakundia', districtId: 'kishoreganj', name: 'Pakundia' },
  { id: 'itna', districtId: 'kishoreganj', name: 'Itna' },
  { id: 'mithamain', districtId: 'kishoreganj', name: 'Mithamain' },
  { id: 'austagram', districtId: 'kishoreganj', name: 'Austagram' },

  // --- CHATTOGRAM DIVISION ---
  // Chattogram District
  { id: 'panchlaish', districtId: 'chattogram-dist', name: 'Panchlaish' },
  { id: 'halishahar', districtId: 'chattogram-dist', name: 'Halishahar' },
  { id: 'khulshi', districtId: 'chattogram-dist', name: 'Khulshi' },
  { id: 'pahartali', districtId: 'chattogram-dist', name: 'Pahartali' },
  { id: 'bakalia', districtId: 'chattogram-dist', name: 'Bakalia' },
  { id: 'kotwali-cth', districtId: 'chattogram-dist', name: 'Kotwali' },
  { id: 'patenga', districtId: 'chattogram-dist', name: 'Patenga' },
  { id: 'double-mooring', districtId: 'chattogram-dist', name: 'Double Mooring' },
  { id: 'potia', districtId: 'chattogram-dist', name: 'Potia' },
  { id: 'hathazari', districtId: 'chattogram-dist', name: 'Hathazari' },
  { id: 'sitakunda', districtId: 'chattogram-dist', name: 'Sitakunda' },
  { id: 'mirsharai', districtId: 'chattogram-dist', name: 'Mirsharai' },
  { id: 'anwara', districtId: 'chattogram-dist', name: 'Anwara' },
  { id: 'raozan', districtId: 'chattogram-dist', name: 'Raozan' },
  { id: 'rangunia', districtId: 'chattogram-dist', name: 'Rangunia' },
  { id: 'fatikchhari', districtId: 'chattogram-dist', name: 'Fatikchhari' },
  { id: 'boalkhali', districtId: 'chattogram-dist', name: 'Boalkhali' },
  // Cox's Bazar
  { id: 'cox-sadar', districtId: 'coxsbazar', name: "Cox's Bazar Sadar" },
  { id: 'ukhiya', districtId: 'coxsbazar', name: 'Ukhiya' },
  { id: 'teknaf', districtId: 'coxsbazar', name: 'Teknaf' },
  { id: 'ramu', districtId: 'coxsbazar', name: 'Ramu' },
  { id: 'chakaria', districtId: 'coxsbazar', name: 'Chakaria' },
  { id: 'moheshkhali', districtId: 'coxsbazar', name: 'Moheshkhali' },
  { id: 'kutubdia', districtId: 'coxsbazar', name: 'Kutubdia' },
  { id: 'pekarua', districtId: 'coxsbazar', name: 'Pekua' },
  // Cumilla
  { id: 'cm-sadar', districtId: 'cumilla', name: 'Cumilla Sadar' },
  { id: 'laksham', districtId: 'cumilla', name: 'Laksham' },
  { id: 'daudkandi', districtId: 'cumilla', name: 'Daudkandi' },
  { id: 'burichang', districtId: 'cumilla', name: 'Burichang' },
  { id: 'chauddagram', districtId: 'cumilla', name: 'Chauddagram' },
  { id: 'barura', districtId: 'cumilla', name: 'Barura' },
  { id: 'chandina', districtId: 'cumilla', name: 'Chandina' },
  { id: 'homna', districtId: 'cumilla', name: 'Homna' },
  { id: 'debidwar', districtId: 'cumilla', name: 'Debidwar' },
  { id: 'muradnagar', districtId: 'cumilla', name: 'Muradnagar' },
  // Noakhali
  { id: 'nk-sadar', districtId: 'noakhali', name: 'Noakhali Sadar' },
  { id: 'begumganj', districtId: 'noakhali', name: 'Begumganj' },
  { id: 'senbagh', districtId: 'noakhali', name: 'Senbagh' },
  { id: 'chatkhil', districtId: 'noakhali', name: 'Chatkhil' },
  { id: 'companiganj-nk', districtId: 'noakhali', name: 'Companiganj' },
  { id: 'hatiya', districtId: 'noakhali', name: 'Hatiya' },
  { id: 'sonaimuri', districtId: 'noakhali', name: 'Sonaimuri' },
  { id: 'subarnachar', districtId: 'noakhali', name: 'Subarnachar' },

  // --- RAJSHAHI DIVISION ---
  // Rajshahi District
  { id: 'boalia', districtId: 'rajshahi-dist', name: 'Boalia' },
  { id: 'motihar', districtId: 'rajshahi-dist', name: 'Motihar' },
  { id: 'rajpara', districtId: 'rajshahi-dist', name: 'Rajpara' },
  { id: 'shahmakdum', districtId: 'rajshahi-dist', name: 'Shahmakdum' },
  { id: 'paba', districtId: 'rajshahi-dist', name: 'Paba' },
  { id: 'godagari', districtId: 'rajshahi-dist', name: 'Godagari' },
  { id: 'tanore', districtId: 'rajshahi-dist', name: 'Tanore' },
  { id: 'bagmara', districtId: 'rajshahi-dist', name: 'Bagmara' },
  { id: 'charghat', districtId: 'rajshahi-dist', name: 'Charghat' },
  { id: 'puthia', districtId: 'rajshahi-dist', name: 'Puthia' },
  { id: 'durgapur-rj', districtId: 'rajshahi-dist', name: 'Durgapur' },
  // Bogura
  { id: 'bg-sadar', districtId: 'bogura', name: 'Bogura Sadar' },
  { id: 'sherpur-bg', districtId: 'bogura', name: 'Sherpur' },
  { id: 'shajahanpur', districtId: 'bogura', name: 'Shajahanpur' },
  { id: 'shibganj-bg', districtId: 'bogura', name: 'Shibganj' },
  { id: 'gabtali', districtId: 'bogura', name: 'Gabtali' },
  { id: 'dhunat', districtId: 'bogura', name: 'Dhunat' },
  { id: 'sariakandi', districtId: 'bogura', name: 'Sariakandi' },
  { id: 'adamdighi', districtId: 'bogura', name: 'Adamdighi' },
  { id: 'kahaloo', districtId: 'bogura', name: 'Kahaloo' },
  { id: 'nandigram', districtId: 'bogura', name: 'Nandigram' },
  // Pabna
  { id: 'pb-sadar', districtId: 'pabna', name: 'Pabna Sadar' },
  { id: 'ishwardi', districtId: 'pabna', name: 'Ishwardi' },
  { id: 'bera', districtId: 'pabna', name: 'Bera' },
  { id: 'chatmohar', districtId: 'pabna', name: 'Chatmohar' },
  { id: 'sujanagar', districtId: 'pabna', name: 'Sujanagar' },
  { id: 'faridpur-pb', districtId: 'pabna', name: 'Faridpur' },
  { id: 'santhia', districtId: 'pabna', name: 'Santhia' },
  { id: 'atgharia', districtId: 'pabna', name: 'Atgharia' },
  // Sirajganj
  { id: 'sj-sadar', districtId: 'sirajganj', name: 'Sirajganj Sadar' },
  { id: 'shahjadpur', districtId: 'sirajganj', name: 'Shahjadpur' },
  { id: 'ullapara', districtId: 'sirajganj', name: 'Ullapara' },
  { id: 'belkuchi', districtId: 'sirajganj', name: 'Belkuchi' },
  { id: 'kazipur', districtId: 'sirajganj', name: 'Kazipur' },
  { id: 'raiganj', districtId: 'sirajganj', name: 'Raiganj' },
  { id: 'tarash', districtId: 'sirajganj', name: 'Tarash' },
  { id: 'kamarkhanda', districtId: 'sirajganj', name: 'Kamarkhanda' },

  // --- KHULNA DIVISION ---
  // Khulna District
  { id: 'kh-sadar', districtId: 'khulna-dist', name: 'Khulna Sadar' },
  { id: 'daulatpur-kh', districtId: 'khulna-dist', name: 'Daulatpur' },
  { id: 'sonadanga', districtId: 'khulna-dist', name: 'Sonadanga' },
  { id: 'khalishpur', districtId: 'khulna-dist', name: 'Khalishpur' },
  { id: 'dumuria', districtId: 'khulna-dist', name: 'Dumuria' },
  { id: 'paikgacha', districtId: 'khulna-dist', name: 'Paikgacha' },
  { id: 'phultala', districtId: 'khulna-dist', name: 'Phultala' },
  { id: 'dighalia', districtId: 'khulna-dist', name: 'Dighalia' },
  { id: 'rupsha', districtId: 'khulna-dist', name: 'Rupsha' },
  { id: 'dacope', districtId: 'khulna-dist', name: 'Dacope' },
  // Jashore
  { id: 'js-sadar', districtId: 'jashore', name: 'Jashore Sadar' },
  { id: 'jhikargacha', districtId: 'jashore', name: 'Jhikargacha' },
  { id: 'keshabpur', districtId: 'jashore', name: 'Keshabpur' },
  { id: 'sharsha', districtId: 'jashore', name: 'Sharsha' },
  { id: 'monirampur', districtId: 'jashore', name: 'Monirampur' },
  { id: 'abhaynagar', districtId: 'jashore', name: 'Abhaynagar' },
  { id: 'bagherpara', districtId: 'jashore', name: 'Bagherpara' },
  { id: 'chaugacha', districtId: 'jashore', name: 'Chaugacha' },
  // Kushtia
  { id: 'kt-sadar', districtId: 'kushtia', name: 'Kushtia Sadar' },
  { id: 'kumarkhali', districtId: 'kushtia', name: 'Kumarkhali' },
  { id: 'veramara', districtId: 'kushtia', name: 'Veramara' },
  { id: 'mirpur-kt', districtId: 'kushtia', name: 'Mirpur' },
  { id: 'khoksa', districtId: 'kushtia', name: 'Khoksa' },
  { id: 'daulatpur-kt', districtId: 'kushtia', name: 'Daulatpur' },

  // --- BARISHAL DIVISION ---
  // Barishal District
  { id: 'br-sadar', districtId: 'barishal-dist', name: 'Barishal Sadar' },
  { id: 'babuganj', districtId: 'barishal-dist', name: 'Babuganj' },
  { id: 'bakarganj', districtId: 'barishal-dist', name: 'Bakarganj' },
  { id: 'banaripara', districtId: 'barishal-dist', name: 'Banaripara' },
  { id: 'gaurnadi', districtId: 'barishal-dist', name: 'Gaurnadi' },
  { id: 'muladi', districtId: 'barishal-dist', name: 'Muladi' },
  { id: 'mehendiganj', districtId: 'barishal-dist', name: 'Mehendiganj' },
  { id: 'agailjhara', districtId: 'barishal-dist', name: 'Agailjhara' },
  { id: 'wazirpur', districtId: 'barishal-dist', name: 'Wazirpur' },
  // Bhola
  { id: 'bh-sadar', districtId: 'bhola', name: 'Bhola Sadar' },
  { id: 'charfasson', districtId: 'bhola', name: 'Charfasson' },
  { id: 'lalmohan', districtId: 'bhola', name: 'Lalmohan' },
  { id: 'borhanuddin', districtId: 'bhola', name: 'Borhanuddin' },
  { id: 'daulatkhan', districtId: 'bhola', name: 'Daulatkhan' },
  { id: 'manpura', districtId: 'bhola', name: 'Manpura' },
  { id: 'tazumuddin', districtId: 'bhola', name: 'Tazumuddin' },

  // --- SYLHET DIVISION ---
  // Sylhet District
  { id: 'sl-sadar', districtId: 'sylhet-dist', name: 'Sylhet Sadar' },
  { id: 'south-surma', districtId: 'sylhet-dist', name: 'South Surma' },
  { id: 'beanibazar', districtId: 'sylhet-dist', name: 'Beanibazar' },
  { id: 'golapganj', districtId: 'sylhet-dist', name: 'Golapganj' },
  { id: 'biswanath', districtId: 'sylhet-dist', name: 'Biswanath' },
  { id: 'fenchuganj', districtId: 'sylhet-dist', name: 'Fenchuganj' },
  { id: 'balaganj', districtId: 'sylhet-dist', name: 'Balaganj' },
  { id: 'gowainghat', districtId: 'sylhet-dist', name: 'Gowainghat' },
  { id: 'jaintiapur', districtId: 'sylhet-dist', name: 'Jaintiapur' },
  { id: 'kanaighat', districtId: 'sylhet-dist', name: 'Kanaighat' },
  { id: 'zakiganj', districtId: 'sylhet-dist', name: 'Zakiganj' },
  { id: 'companiganj-sl', districtId: 'sylhet-dist', name: 'Companiganj' },
  // Moulvibazar
  { id: 'mv-sadar', districtId: 'moulvibazar', name: 'Moulvibazar Sadar' },
  { id: 'sreemangal', districtId: 'moulvibazar', name: 'Sreemangal' },
  { id: 'kulaura', districtId: 'moulvibazar', name: 'Kulaura' },
  { id: 'kamalganj', districtId: 'moulvibazar', name: 'Kamalganj' },
  { id: 'rajnagar', districtId: 'moulvibazar', name: 'Rajnagar' },
  { id: 'barlekha', districtId: 'moulvibazar', name: 'Barlekha' },
  { id: 'juri', districtId: 'moulvibazar', name: 'Juri' },

  // --- RANGPUR DIVISION ---
  // Rangpur District
  { id: 'rp-sadar', districtId: 'rangpur-dist', name: 'Rangpur Sadar' },
  { id: 'mithapukur', districtId: 'rangpur-dist', name: 'Mithapukur' },
  { id: 'pirganj-rp', districtId: 'rangpur-dist', name: 'Pirganj' },
  { id: 'badarganj', districtId: 'rangpur-dist', name: 'Badarganj' },
  { id: 'kaunia', districtId: 'rangpur-dist', name: 'Kaunia' },
  { id: 'pirgacha', districtId: 'rangpur-dist', name: 'Pirgacha' },
  { id: 'taraganj', districtId: 'rangpur-dist', name: 'Taraganj' },
  { id: 'gangachara', districtId: 'rangpur-dist', name: 'Gangachara' },
  // Dinajpur
  { id: 'dj-sadar', districtId: 'dinajpur', name: 'Dinajpur Sadar' },
  { id: 'birganj', districtId: 'dinajpur', name: 'Birganj' },
  { id: 'phulbari', districtId: 'dinajpur', name: 'Phulbari' },
  { id: 'parbatipur', districtId: 'dinajpur', name: 'Parbatipur' },
  { id: 'khansama', districtId: 'dinajpur', name: 'Khansama' },
  { id: 'kaharole', districtId: 'dinajpur', name: 'Kaharole' },
  { id: 'bochaganj', districtId: 'dinajpur', name: 'Bochaganj' },
  { id: 'birol', districtId: 'dinajpur', name: 'Birol' },
  { id: 'chirirbandar', districtId: 'dinajpur', name: 'Chirirbandar' },
  { id: 'fulbari', districtId: 'dinajpur', name: 'Fulbari' },
  { id: 'nawabganj-dj', districtId: 'dinajpur', name: 'Nawabganj' },
  { id: 'ghoraghat', districtId: 'dinajpur', name: 'Ghoraghat' },
  { id: 'hakimpur', districtId: 'dinajpur', name: 'Hakimpur' },

  // --- MYMENSINGH DIVISION ---
  // Mymensingh District
  { id: 'mm-sadar', districtId: 'mymensingh-dist', name: 'Mymensingh Sadar' },
  { id: 'muktagacha', districtId: 'mymensingh-dist', name: 'Muktagacha' },
  { id: 'phulpur', districtId: 'mymensingh-dist', name: 'Phulpur' },
  { id: 'gauripur', districtId: 'mymensingh-dist', name: 'Gauripur' },
  { id: 'ishwarganj', districtId: 'mymensingh-dist', name: 'Ishwarganj' },
  { id: 'phulbaria', districtId: 'mymensingh-dist', name: 'Phulbaria' },
  { id: 'trisal', districtId: 'mymensingh-dist', name: 'Trisal' },
  { id: 'bhaluka', districtId: 'mymensingh-dist', name: 'Bhaluka' },
  { id: 'gofargaon', districtId: 'mymensingh-dist', name: 'Gofargaon' },
  { id: 'nandail', districtId: 'mymensingh-dist', name: 'Nandail' },
  { id: 'haluaghat', districtId: 'mymensingh-dist', name: 'Haluaghat' },
  { id: 'dhobaura', districtId: 'mymensingh-dist', name: 'Dhobaura' },
  { id: 'tarakanda', districtId: 'mymensingh-dist', name: 'Tarakanda' },
  // Jamalpur
  { id: 'jm-sadar', districtId: 'jamalpur', name: 'Jamalpur Sadar' },
  { id: 'sarishabari', districtId: 'jamalpur', name: 'Sarishabari' },
  { id: 'islampur', districtId: 'jamalpur', name: 'Islampur' },
  { id: 'dewanganj', districtId: 'jamalpur', name: 'Dewanganj' },
  { id: 'bakshiganj', districtId: 'jamalpur', name: 'Bakshiganj' },
  { id: 'madarganj', districtId: 'jamalpur', name: 'Madarganj' },
  { id: 'melandaha', districtId: 'jamalpur', name: 'Melandaha' },
];

export const CONDITIONS = ['Like New', 'Good', 'Fair', 'Poor', 'Donation'] as const;

export const CLASSES = [
  'Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5', 
  'Class 6', 'Class 7', 'Class 8', 'Class 9', 'Class 10', 
  'Class 11', 'Class 12', 'Other'
] as const;